### ISSUE TITLE
Installment widget errors on Shopify

### ISSUE THREAD

**Issue by brendanatme** [sezzle/static-widgets#24]
Hi there,

I just implemented the [installment widget](https://github.com/sezzle/static-widgets/blob/production/src/sezzle-checkout-installment-widget/sezzle-checkout-installment-widget.js) in a Shopify checkout and wanted to highlight a number or errors I ran into.

I've fixed the issues in my own implementation, so I don't require any response, just thought you would want to know about these.

### Shopify-specific implementation
 
On [line 9](https://github.com/sezzle/static-widgets/blob/d750a8ebd523430f00447c4628573d2b7d6f7f38/src/sezzle-checkout-installment-widget/sezzle-checkout-installment-widget.js#L9):

```
// let sezzlePaymentLine = document.querySelector('[alt="Sezzle Staging"]').parentElement.parentElement.parentElement; //Shopify
```

This element does not exist in the Shopify checkout -- is the "Staging" part of "Sezzle Staging" a typo?

### Browser support

- IE 10 and lower do not support the `let` keyword
- IE 11 and lower do not support template strings

I know, I don't want to support IE either, but some customers do use these browsers and I imagine other retailers will need to support these browsers at checkout

**Comment by aholdahl** [comment]
Thank you for the insights - I have added these changes for the next release.
