### ISSUE TITLE
Sezzle widget styling issues

### ISSUE THREAD

**Issue by glennrocksvb** [sezzle/static-widgets#37]
I see 2 styling issues which can be avoided with a simple fix.

1. The widget container `sezzle-checkout-button-wrapper` has `sezzle-modal-link` class name and styled with `cursor: pointer`. But this element is not clickable. The info icon inside which has `sezzle-modal-open-link` class is the one clickable with click event listener for the modal. Please remove the inline style `cursor: pointer` so that merchants don't have to override it.

2. The `sezzle-payment-amount` element inside the widget has hardcoded `font-size: 12px`. There is a config to set `fontSize` for its parent element. The payment amount element should have `font-size: inherit` by default to inherit the font-size set for its parent. Fixing this on your end should also help merchants to not have extra code to override the font size.

Thanks!

**Comment by aholdahl** [comment]
`cursor: pointer` styling has been removed from the widget text per your request. 

`.sezzle-payment-amount` does not have font size hard-coded, but inherits from `.sezzle-button-text` - this can be overridden via config option `fontSize` (number value only - px is assumed).

**Comment by glennrocksvb** [comment]
@aholdahl, thanks for the cursor fix.

For the hardcoded font size, it is set to 12px by default in https://github.com/sezzle/static-widgets/blob/production/css/global.scss#L19

Then even if you set `fontSize` config option, it is only applied to the `.sezzle-button-text`

![image](https://user-images.githubusercontent.com/30279453/111819852-109f0780-889e-11eb-8119-5c6febba5dbc.png)

but not to `.sezzle-payment-amount`

![image](https://user-images.githubusercontent.com/30279453/111820104-54920c80-889e-11eb-88a0-f0d73cceabe5.png)

**Comment by glennrocksvb** [comment]
I checked the code and `fontSize` is only set to one element which is the first child of the first child of the `renderElement`. And that is the `.sezzle-button-text` element.

![image](https://user-images.githubusercontent.com/30279453/111820739-16491d00-889f-11eb-9e6f-f7e48a1f4104.png)

**Comment by aholdahl** [comment]
@glennrocksvb Thanks for the details - this should be fixed now.

**Comment by glennrocksvb** [comment]
@aholdahl, thanks for the font-size fix.

Btw, why was the `font-weight: 900` removed in `.sezzle-payment-amount` CSS when you did the cursor fix?

https://github.com/sezzle/static-widgets/commit/2733920fe50ab60e6a4d2f0025fadaf69bb91fae#diff-e355efd1f05ed677ffae7b396a78251b7156f50e77010fd266e16e28976ab7d3R21

Now the amount in the widget is no longer in bold.

**Comment by glennrocksvb** [comment]
I confirm the font-weight issue on the amount is now fixed.
