### ISSUE TITLE
Modal content not updated when alterPrice is called

### ISSUE THREAD

**Issue by glennrocksvb** [sezzle/static-widgets#39]
We have a product page with multi-products that have a dropdown of items. When an item is selected in the dropdown, it updates the corresponding price without page reload. In that case, we call `renderSezzle.alterPrice(newPrice)` to update the Sezzle widget. It updates the widget correctly but when you click the info icon, the modal still shows the content for the default price that was initially set on page load.

Please see a demo of the issue at https://jsfiddle.net/1beqy2nh/1/

**Comment by glennrocksvb** [comment]
The Sezzle config in the jsfiddle demo is set as:

```
 minPrice: 10000,
 minPriceLT: 75000,
 maxPrice: 1000000,
 bestAPR: 9.9
```
Here's the steps to reproduce the issue in the demo:

1. On page load, it correctly displays the LT widget for the default selected item with price of $1,000.
2. Click info icon. It correctly displays the LT modal for $1,000.
3. Select a different item with price of $500. It correctly updates the widget for pay in 4 payment option.
4. Click info icon. It still displays the LT modal for $1,000. It should display the regular pay in 4 modal.
5. Select another item with price of $2,000. It correctly updates the LT widget.
6. Click info icon. It still displays the LT modal for $1,000. It should display the LT modal for $2,000.

**Comment by aholdahl** [comment]
alterPrice is updated now to re-render modal

**Comment by glennrocksvb** [comment]
Thanks for the fix @aholdahl. I confirm it is working.
