### ISSUE TITLE
Monthly payment calculation is incorrect in LT modal

### ISSUE THREAD

**Issue by glennrocksvb** [sezzle/static-widgets#40]
It seems that after the modal re-render fix (00d0bed4ca2ca29164335f24da5adfe21f98f375), the calculation for the monthly payment started not working correctly?

Using the old jsfiddle which still has the modal re-render issue, I see that on page load for the default selected item "Item 1" which has a price of $3,291.20, the widget text says the lowest monthly payment is $603.33 and when you open the modal, it correctly shows the same lowest monthly payment amount.

https://jsfiddle.net/1beqy2nh/2/

![image](https://user-images.githubusercontent.com/30279453/112361741-f3e54400-8c90-11eb-8f0a-f40ad8a86de7.png)

But for this updated jsfiddle with the latest fix as of today (d9021fbaf358920ca62cc6aa72f3a129c2df12b3), I see that the widget text says the lowest monthly payment is $603.33 but in the modal the lowest monthly payment is $75.42.

https://jsfiddle.net/3b61z9dg/

![image](https://user-images.githubusercontent.com/30279453/112361884-137c6c80-8c91-11eb-9232-8995e0bc2ba6.png)

**Comment by aholdahl** [comment]
Sorry for the delay - this should be fixed now!

**Comment by glennrocksvb** [comment]
@aholdahl, thanks for the update. But I don't see any commits? The latest commit was from yesterday for the 13px font-size fix.

**Comment by aholdahl** [comment]
Sorry about that - seems my commit didn't go through. It is up now.

**Comment by glennrocksvb** [comment]
Thanks @aholdahl. The fix works.

**Comment by glennrocksvb** [comment]
@aholdahl, I tested your fix again but it seems like it just partially fixes the issue.

I updated the jsfiddle with your latest commits at the new link below.

https://jsfiddle.net/92ecdxz4/

When you choose Item 1 with price of $750, it shows lowest monthly payment of $68.74 in the widget text but the modal shows $137.49.
![image](https://user-images.githubusercontent.com/30279453/112679602-989a8980-8e29-11eb-9c8c-b4baffd89acc.png)


When you choose Item 2 with price of $2,000, it shows lowest monthly payment of $366.63 in the widget text and the modal shows the same lowest monthly payment.
![image](https://user-images.githubusercontent.com/30279453/112679664-aa7c2c80-8e29-11eb-89e7-8494ad537a41.png)

**Comment by aholdahl** [comment]
@glennrocksvb Thank you for you continued feedback. This issue is now resolved.

**Comment by glennrocksvb** [comment]
@aholdahl, thanks for the fix. But the bundle JS seems to be not updated yet.

https://github.com/sezzle/static-widgets/blob/production/dist/bundle.js

It says the latest commit was from yesterday.

**Comment by aholdahl** [comment]
Ugh, TGIF! Sorry about that, it is pushed now.

**Comment by glennrocksvb** [comment]
@aholdahl , thanks!
